// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EndpointsColumns holds the columns for the "endpoints" table.
	EndpointsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uri", Type: field.TypeString, Unique: true},
		{Name: "content", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// EndpointsTable holds the schema information for the "endpoints" table.
	EndpointsTable = &schema.Table{
		Name:       "endpoints",
		Columns:    EndpointsColumns,
		PrimaryKey: []*schema.Column{EndpointsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EndpointsTable,
	}
)

func init() {
}
