// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/1nv8rzim/otn/ent/endpoint"
	"github.com/1nv8rzim/otn/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	endpointFields := schema.Endpoint{}.Fields()
	_ = endpointFields
	// endpointDescURI is the schema descriptor for uri field.
	endpointDescURI := endpointFields[0].Descriptor()
	// endpoint.URIValidator is a validator for the "uri" field. It is called by the builders before save.
	endpoint.URIValidator = endpointDescURI.Validators[0].(func(string) error)
	// endpointDescContent is the schema descriptor for content field.
	endpointDescContent := endpointFields[1].Descriptor()
	// endpoint.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	endpoint.ContentValidator = endpointDescContent.Validators[0].(func(string) error)
	// endpointDescCreatedAt is the schema descriptor for created_at field.
	endpointDescCreatedAt := endpointFields[2].Descriptor()
	// endpoint.DefaultCreatedAt holds the default value on creation for the created_at field.
	endpoint.DefaultCreatedAt = endpointDescCreatedAt.Default.(func() time.Time)
}
